### PR TITLE
Introduce color tokens in the color palette page

### PR DESCRIPTION
**Pull request by huayunh**
Fixes BLUI-3558

#### Changes proposed in this Pull Request:
- Added color tokens to http://localhost:3000/style/color
- Added text-decoration to link styles
- minor fixes here and there

#### Screenshots:
image

### CODE REVIEW

**Comment by emclaug2** [comment]
Is this something that we want to have included in the R25 release?

**Comment by huayunh** [comment]
@emclaug2 No. This cannot be merged to docit master until at least a new color package and themes packages are published

**Review by ektasawant — COMMENTED** [review]
Changes looks good. 1 small observation.

Can we change color of highlighted section as per accessibility (something that I found useful in accessibility workshop 😬  )
Screenshot 2022-10-13 at 3 27 21 PM

**Comment by huayunh** [comment]
this entire page is constructed as if we have already updated our colors and themes package.

That small print there is currently not accessible, but will become accessible once we publish our new themes

**Comment by ektasawant** [comment]
Changes looks good 👍

**Pull request merged**
