### PR TITLE
Update Theme Dates

### PR DESCRIPTION
**Pull request by joebochill**
#### Changes proposed in this Pull Request:
- Update dates for the remainder of 2022

### CODE REVIEW

**Review by huayunh — CHANGES_REQUESTED** [review]
Update comments here too https://github.com/brightlayer-ui/doc-it/blob/dev/src/__configuration__/themes/_schedule.ts

**Comment by joebochill** [comment]
I'm not going to have the time to make code changes this week, so if somebody else wants to polish this off, feel free.

**Comment by huayunh** [comment]
will leave that to all the admins here since this is the dev branch

**Comment by joebochill** [comment]
> will leave that to all the admins here since this is the dev branch

Don't forget, the dev branch can be updated by any PR into dev as well...like a valentines day theme, for example 😛

**Comment by daileytj** [comment]
whoops... accidentally closed this somehow

**Review by huayunh — APPROVED** [review]

**Review by daileytj — APPROVED** [review]

**Pull request merged**
