### PR TITLE
Docit Image Updates

### PR DESCRIPTION
**Pull request by huayunh**
Fixes BLUI-2686

#### Changes proposed in this Pull Request:
- Fix a few docit images that does not reflect the latest design intent

### CODE REVIEW

**Comment by huayunh** [comment]
@mvbela 

It appears that you mostly replaced button texts from ALL CAPS to use lower cases. 

The purpose of this story was mainly to focus on fixing images on the navigation page. Like this one:
- it does not make any sense for all the notification icons
- The icons have different colors
- The "All Locations" text in the app bar on the top right corner has the wrong typography setting

image

**Review by huayunh — COMMENTED** [review]
# 1
I noticed a mix of gray500 and black 500 in these two files: `src/app/assets/design-patterns/lists/notification-buckets-1.png` `src/app/assets/design-patterns/lists/notification-buckets-2.png`
image

# 2 
src/app/assets/design-patterns/lists/notification-list-desktop.png
Why did you changed "export" to all caps here?

# 3
src/app/assets/design-patterns/navigation/collapsible.png
why was the hamburger menu icon and the close icon changed?
Screen Shot 2022-02-09 at 4 37 41 PM
It makes no sense to show a logo when collapsed, and hamburger menu when expanded.

# 4
src/app/assets/design-patterns/navigation/content-cover-desktop.png
Same question. Why was the close icon removed when the drawer expand?

(I see that you made similar changes to many other drawers)

# 5
src/app/assets/design-patterns/navigation/content-cover.png
src/app/assets/design-patterns/navigation/content-resize.png
Why was the one on the left shrinked?
image

# 6 
src/app/assets/design-patterns/navigation/divider-do.png 
want to get rid of the "Power Xpert Blue" in the drawer header?

# 7 
src/app/assets/design-patterns/navigation/navigation-persistent.png
why was the navigation rail enlarged? (I would not recommend showing a 72dp rail without text labels under those icons)
The card shadow should stay at 1dp. It looks like the latest version is using a 4dp shadow.

# 8
src/app/assets/design-patterns/navigation/panel-specs-mobile.png 
overflowed shape

# 9 
src/app/assets/design-patterns/navigation/anatomy.png
The shadow outside the drawer gets extra dark

**Comment by huayunh** [comment]
@mvbela , I encourage you to double-check your own work using this "Files Changed" tab
Screen Shot 2022-02-09 at 4 54 36 PM

**Comment by huayunh** [comment]
I can verify that everything runs properly technical-wise with no RSOD or console errors. @mvbela, just waiting for your small update I mentioned in the chat, and we shall be good to go.

**Review by emclaug2 — APPROVED** [review]
Eyeballing the images these look good.

**Pull request merged**
