### PR TITLE
BLUI-2241, Color Accessibility Tool on Docit

### PR DESCRIPTION
**Pull request by huayunh**
Fixes BLUI-2241

#### Changes proposed in this Pull Request:
- Ways to view colors in different color spaces
- Ways to view its contrast ratio
- Ways to "deeplink" into a color
- Removed some outdated material in preparation for theme accessibility audit 

#### Screenshots:

https://user-images.githubusercontent.com/8997218/150290442-9cf2f142-dcf4-46a8-b0ba-fa910831bc6a.mov

#### To Test:
- Play around color patches in http://localhost:3000/style/color?category=ui&name=darkBlack&weight=900

### CODE REVIEW

**Comment by jeffvg** [comment]
I'm not familiar with pantone but should pantone value be available for any color we have?

**Comment by huayunh** [comment]
> pantone value be available for any color we have?

I am not 100% sure with the Pantone color space either, but they seem to be more granular for certain spectrums and less diverse somewhere else. You can play around with this tool here: https://www.ginifab.com/feeds/pms/cmyk_to_pantone.php

**Comment by huayunh** [comment]
Update: using a better maintained Pantone converter now, which always returns the nearest pantone color

**Comment by huayunh** [comment]
Alright... talked to industrial designers and they are saying that they keep their own Pantone system, and that these are not a 1-1 translation. Removing the Pantone chips.

**Review by andrupu — APPROVED** [review]

**Comment by jeffvg** [comment]
is there anything we can do to get close button and dismiss to work for bottom sheet on device? Unable to close but could be my system

image

**Review by jeffvg — APPROVED** [review]

**Pull request merged**
