### PR TITLE
Tidy up docit mui v5 migration

### PR DESCRIPTION
**Pull request by daileytj**
Fixes BLUI-3671.

#### Changes proposed in this Pull Request:
- Fix typography table styles
- Fix table of content styles and typography
- Fix some responsiveness issues with table of contents
- Cean up merge conflicts with dev

This should address the remaining issues discussed in the this [PR](https://github.com/brightlayer-ui/doc-it/pull/601)

### CODE REVIEW

**Comment by daileytj** [comment]
The link checker is failing both locally and on CI... not sure what we want to do about this since there seem to be a lot of "broken links"

**Comment by joebochill** [comment]
> The link checker is failing both locally and on CI... not sure what we want to do about this since there seem to be a lot of "broken links"

Verify that the 'broken' links actually do work when you open them in a browser. Disable the link checking for CI and we will run it as a manual check before we do any big deployments.

**Comment by joebochill** [comment]
You'll need to fix the imports from all of the content @huayunh added:
image

**Comment by daileytj** [comment]
@joebochill good eye. I had a tough time with that merge.

**Comment by daileytj** [comment]
@joebochill... I must not have run this after I merged this 🤦‍♂️. I'm in there now, I see what is going on. Basically, just have to migrate the stuff that got in early to muiv5. On it!

**Comment by huayunh** [comment]
This spacing right here is missing
image

**Comment by huayunh** [comment]
Table of content should not look like this between 1200px and 1280px

image

**Comment by huayunh** [comment]
This might be my mistake. The design audit page currently has an extra `/` in its URL
image

**Comment by huayunh** [comment]
Dev resources mobile view, these two icons are not aligned
image

**Comment by huayunh** [comment]
Apps built using BLUI, this page's mobile view is not working. Should be a card view

image

**Comment by huayunh** [comment]
Color stripe & list item tag color:
image

**Comment by huayunh** [comment]
Monospaced code inline blocks font size
image

**Comment by jeffvg** [comment]
> 

at 800 width these look ok but when we set to 799 width we drop the github icon
image
image

**Comment by huayunh** [comment]
Color palette, when the screen width is between 900 - 930, the palette is wrapped in a wrong way. Somewhere in the code, we need to change the flexbox style's `justify-content` from `space-between` to `flex-start` 
image

**Comment by huayunh** [comment]
Dark theme, icon library page, the side panel looks... incorrect. The tags field is too bright, and the three developer usage panel is picking up a strange color too.

image

**Comment by daileytj** [comment]
> 1200px and 1280px

This is not being altered at this stage. I spent more than a day going back and forth with multiple people about how this should be done with the new breakpoint defaults in mui5. This is the result of those discussions.

**Comment by daileytj** [comment]
Update: I'll do what I can to address what comes through here, but this issue was scoped to deal with the comments that are currently in the branch this is going to be merged into. If there are issues present here that are currently in the target branch they will need to be addressed in another story.

**Comment by huayunh** [comment]
I think there might be some misunderstanding here. Let me clarify— I am pointing out that there should not be an “active state” on the TOC item. At that viewport width, The TOC is being embedded, instead of fixed. There should not be an active / “current” TOC item being highlighted

**Comment by daileytj** [comment]
> Color stripe & list item tag color. Note that this looks extra wrong in the dark theme, where the color appears extra bright image

Where is this? I'm not seeing this. Is it every example or a select few?

**Comment by jeffvg** [comment]
in all looks like you're covering items needed from migrate to muiv5 PR. 

- also to note setting browser sizes via dev tools versus manually resizing the window...
When using widths 1440, 1024, 768 via the button in dev tools all seems good with exception of "apps built using blui page" and the dev resources page dropping icons....

**Comment by daileytj** [comment]
> in all looks like you're covering items needed from migrate to muiv5 PR.
> 
> * also to note setting browser sizes via dev tools versus manually resizing the window...
>   When using widths 1440, 1024, 768 via the button in dev tools all seems good with exception of "apps built using blui page" and the dev resources page dropping icons....

Just pushed a few fixes. Should cover everything with a thumbs up response above

**Comment by daileytj** [comment]
> Monospaced code inline blocks font size image

Looks like this could have been done on purpose to make all the code blocks 12px. As it stands in dev there are 2 different sizes for code blocks, but a hard coded size for the update. https://brightlayer-ui-dev.github.io/development/environment uses 12px while https://brightlayer-ui-dev.github.io/style/themes#react snippet uses 16px

**Comment by huayunh** [comment]
> Where is this? I'm not seeing this. Is it every example or a select few?

I do not have the computer with me at the moment, but this looks like it comes from the themes page

**Comment by joebochill** [comment]
This is looking great @daileytj — appreciate all of the extra effort on this, including the scope creep.

To weigh in on the code block discussion...the new style defined for dev-docs uses 14 (0.875rem) for inline code. We should be doing the same for doc-it (I would expect that the markdownMapping components should have set this correctly, but there may be something else overriding it like in index.css).

If you've got everything from above handled with the exception of the tags panel in the icon drawer, I would draw a line in the sand there. Anything else (especially if it's (holiday) theme-related) should be a new issue. I'm pretty sure I already logged an issue to fix the themes as they are very very broken from due to some changes in theme structure for MUI 5 and how we do overrides for holiday themes...that is a story of work on its own.

**Comment by huayunh** [comment]
> at 800 width these look ok but when we set to 799 width we drop the github icon
> image
> image

Because there is a “view on GitHub” button below. This was a conscious design choice

**Comment by huayunh** [comment]
I think dev doc used body2 for its paragraph style while docit used body1. We probably want to unify these. I am happy either way … maybe slightly leaning towards body 1

**Comment by jeffvg** [comment]
I pulled down fresh this morning and noticed the warning about pseudo class first-child that would happen once in a few clicks to happening 14 times in one click. If you scroll to the bottom of "apps using blui" page then nav to roadmap page you should see this 14 times

image

**Comment by jeffvg** [comment]
added issue for first-child warnings
https://github.com/brightlayer-ui/doc-it/issues/615

**Comment by jeffvg** [comment]
> 

yeah, was only calling this out because its resizing or padding the "bug" icon and not the build "check icon" throwing off the alignment that you mentioned before here
image

**Comment by daileytj** [comment]
@jeffvg @huayunh Are we good to go on what is here?

**Review by jeffvg — APPROVED** [review]

**Pull request merged**
