### PR TITLE
Feature/2794 hide eaton logo

### PR DESCRIPTION
**Pull request by ektasawant**
Fixes 2794 .

#### Changes proposed in this Pull Request:
- Hide Eaton logo from icon library page. 

#### Screenshots:
Screenshot 2022-01-31 at 4 09 50 PM

#### To Test:
Search `Eaton` it should hide logos.
Deep links are working:
- http://localhost:3000/style/iconography?icon=Eaton&isMaterial=false
- http://localhost:3000/style/iconography?icon=EatonTagline&isMaterial=false
- http://localhost:3000/style/iconography?icon=EatonTwoTone&isMaterial=false

### CODE REVIEW

**Comment by jeffvg** [comment]
you can update the markdown file for https://brightlayer-ui-dev.github.io/development/testing
The Jasmine link has moved for this,

the new link is
https://jasmine.github.io/pages/getting_started.html

the old link is
https://jasmine.github.io/2.0/introduction

**Comment by ektasawant** [comment]
> link checker is failing in CI.
> 
> you can update the markdown file for https://brightlayer-ui-dev.github.io/development/testing The Jasmine link has moved for this,
> 
> the new link is https://jasmine.github.io/pages/getting_started.html
> 
> the old link is https://jasmine.github.io/2.0/introduction

Done please review.

**Comment by huayunh** [comment]
I haven't checked anything yet, but I like that you still keep the deep link working

**Review by jeffvg — APPROVED** [review]

**Review by emclaug2 — APPROVED** [review]

**Comment by emclaug2** [comment]
Code changes look good and the deep link works.

**Pull request merged**
